# Project: Project14
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Untitled15.o
LINKOBJ  = Untitled15.o
LIBS     = -L"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib" -L"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/include" -I"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/include" -I"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/ProgramData/App-V/D4663F9D-AAE5-4622-8BCC-829CA204AC74/7DBF48A7-0E91-4170-A79C-F511D40FAC9E/Root/VFS/ProgramFilesX86/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project14.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Untitled15.o: Untitled15.c
	$(CC) -c Untitled15.c -o Untitled15.o $(CFLAGS)
